### ISSUE TITLE
Mail not moved and processed only once

### ISSUE THREAD

**Issue by fxy-afau** [jgosmann/dmarc-metrics-exporter#34]
Hello,

The mails are now processed but they are not moved in done or error folders.

And if I put another reports after they are not processed.

I need to restart my docker container to process the mail once.

**Comment by jgosmann** [comment]
Can you provide the (debug) log?

**Comment by fxy-afau** [comment]
```Error while processing server responses.
Traceback (most recent call last):
  File "/venv/lib/python3.7/site-packages/dmarc_metrics_exporter/imap_client.py", line 184, in _process_responses
    async for parse_tree in parse_incremental(response_grammar, reader):
  File "/venv/lib/python3.7/site-packages/bite/parse_functions.py", line 81, in parse_incremental
    parse_tree = await grammar.parse(buffer, 0)
  File "/venv/lib/python3.7/site-packages/bite/parsers.py", line 356, in parse
    parsed_nodes.append(await parser.parse(buf, current_loc))
  File "/venv/lib/python3.7/site-packages/bite/transformers.py", line 90, in parse
    self.name, await self.parser.parse(buf, loc), self.transform
  File "/venv/lib/python3.7/site-packages/bite/parsers.py", line 600, in parse
    raise UnmetExpectationError(self, loc)
bite.parsers.UnmetExpectationError: expected b'\r\n' at position 25```

**Comment by jgosmann** [comment]
Can you try again with version 0.9.0 and provide the log output of that version? It should provide a little bit more detail on why the parsing fails.

**Comment by fxy-afau** [comment]
I can't install the new version, I have the following error :
```
ERROR: Could not find a version that satisfies the requirement dmarc-metrics-exporter==0.9.0 (from versions: 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.5.1.dev0, 0.5.1, 0.6.0, 0.6.1, 0.6.2, 0.7.0, 0.8.0, 0.8.1)
ERROR: No matching distribution found for dmarc-metrics-exporter==0.9.0
```

**Comment by Arteneko** [comment]
I also encounter some similar issue (notably that, on first run, reports are properly processed, but from there on it will stop processing/importing the reports at a random point in time without any visible crash log).

I don't have the spoons to diagnose that right now, but I'll have to check it at some point so I'm keeping tabs on this issue and I'll let you know if/when I find something.

**Comment by jgosmann** [comment]
> I can't install the new version

Which Python version are you using? I dropped support for Python 3.7 with 0.9.0.

**Comment by fxy-afau** [comment]
Ok after upgrading to python 3.11, the program run, the first processing is ok, but if I drop new reports in mailbox there is an error :
```
Error while processing server responses.
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/dmarc_metrics_exporter/imap_client.py", line 184, in _process_responses
    async for parse_tree in parse_incremental(response_grammar, reader):
  File "/venv/lib/python3.11/site-packages/bite/parse_functions.py", line 81, in parse_incremental
    parse_tree = await grammar.parse(buffer, 0)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/bite/parsers.py", line 351, in parse
    parsed_nodes.append(await parser.parse(buf, current_loc))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/bite/transformers.py", line 92, in parse
    self.name, await self.parser.parse(buf, loc), self.transform
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/bite/parsers.py", line 595, in parse
    raise UnmetExpectationError(self, loc, buf)
bite.parsers.UnmetExpectationError: expected b'\r\n' at position 25

Input: bytearray(b'* 2 FETCH (UID 60 RFC822 {146976}\r\nReceived: from ... NCjx0ZCB2\r\nYWxpZ249Im1pZGRsZSIgYWxpZ249ImNlbnRlciIgd2lkdGg9IjEwMCI')
                                  ^ location of error
```

**Comment by jgosmann** [comment]
Please check whether the problem is fixed with version 0.9.1.

**Comment by jgosmann** [comment]
You will need bite-parser 0.2.2 as that is [the actual bugfix](https://github.com/jgosmann/bite-parser/commit/8de1556b0473bcc9580c788df50724d8ef74481f). I thought, [this line in the pyproject.toml](https://github.com/jgosmann/dmarc-metrics-exporter/blob/main/pyproject.toml#L28) would ensure that dmarc-metrics-exporter 0.9.1 will install at least bite-parser 0.2.2. 🤔

**Comment by Arteneko** [comment]
I was testing the project on my dev env with bite-parser 0.2.1 and 0.2.2 to see if I could reproduce it, but reading your bugfix makes it kinda obvious that it wasn't a guaranteed bug reproduction >>

Made a poetry devenv on my server with the same config and with bite-parser 0.2.2 now works as expected even with the emails previously provoking a response failure.

I'm gonna see to update the nixpkgs' dmarc exporter and bite-parser versions and I'll keep an eye out for any new failure.

**Comment by Arteneko** [comment]
Tested with 9.1, the parsing errors aren't appearing anymore, and everything polls as expected. Thanks a lot!

**Comment by fxy-afau** [comment]
Yes I confirm, it works as expected now, thank you !
