### ISSUE TITLE
support for json logging

### ISSUE THREAD

**Issue by schewara** [jgosmann/dmarc-metrics-exporter#35]
For better integration into the whole observability ecosystem, it would be great if the exporter would also allow to configure a json logging format by integrating python-json-logger or structlog.

**Comment by jgosmann** [comment]
Great suggestion. Might take a while until I get around to implement this, but contributions would be welcome.

**Comment by schewara** [comment]
I can try, but not promise. :wink:

Personally I think structlog is way more powerful then the python-json-logger, but would like to know, which option you would prefer?

**Comment by jgosmann** [comment]
I am not familiar with either and they both seem used by a fair bit of projects. Thus, I do not really have a preference.

**Comment by jgosmann** [comment]
I had a look at this today. I wouldn't use python-json-logger as the maintenance situation is currently unclear (madzak/python-json-logger#187). structlog seems to be better maintained, but also more complex. There are a few points that need attention when introducing this:

* How to handle the configuration? Currently, this can be done simply via the JSON configuration file, but this does not seem to be easily possible with structlog. Probably there are configuration properties which do not need to or should not be configurable via the dmarc-metrics-exporter file. However, some control is necessary like log level and filtering loggers.
* Uvicorn uses the standard library's logging framework (I think). This needs to be connected up properly (which also at least requires reading and understanding quite a bit of [documentation](https://www.structlog.org/en/stable/standard-library.html)).

**Comment by schewara** [comment]
True, there has not been much progress in getting json logging support in Python and the [docs](https://docs.python.org/3/howto/logging-cookbook.html#implementing-structured-logging) also only provides some quirky solution to it.

Another alternative which i stumbled on is [stlog](https://fabien-marty.github.io/stlog/), but seems rather new and time will tell how this develops.

The [OpenTelemetry Python SDK](https://github.com/open-telemetry/opentelemetry-python/tree/main/docs/examples/logs) is also still marked as experimental, but could be the preferred way forward now that Prometheus is also starting to support remote writes for [OpenTelemetry metrics](https://prometheus.io/docs/prometheus/latest/feature_flags/#otlp-receiver).
